# Generated by Django 5.0.6 on 2024-07-13 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_quiz_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='subject',
            field=models.CharField(default='English', max_length=25),
        ),
    ]
