# Generated by Django 5.0.6 on 2024-07-14 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_learning_subject_videos_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
