# Generated by Django 5.0.6 on 2024-07-14 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_videos_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='content',
        ),
        migrations.AddField(
            model_name='videos',
            name='download_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
