# Generated by Django 5.0.6 on 2024-07-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_videos_content_videos_download_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='learning',
            name='content',
            field=models.FileField(upload_to='media/'),
        ),
    ]
