# Generated by Django 5.0.6 on 2024-07-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_overallfile_alter_learning_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
