# Generated by Django 5.0.6 on 2024-07-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_learning_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverallFile',
        ),
    ]
